var finalObj = [];
var fs = require("fs");
var finalObj1 = [];
//1.
var dimension1 = {};
  var hierarchy1 = {};
    var level1_1 = {};
      var member1_1_1 = {};
    var level1_2 = {};
      var member1_2_1 ={};
      var member1_2_2 ={};
      var member1_2_3 ={};
      var member1_2_4 ={};
      var member1_2_5 ={};
      var member1_2_6 ={};
      var member1_2_7 ={};


//2.
var dimension2 = {};
  var hierarchy2 = {};
    var level2_1 = {};
      var member2_1_1 = {};
      var member2_1_2 = {};
      var member2_1_3 = {};


//3.
var dimension3 = {};
  var hierarchy3 = {};
    var level3_1 = {};
      var member3_1_1 = {};
    var level3_2 = {};
      var member3_2_1 = {};
      var member3_2_2 = {};
      var member3_2_3 = {};
      var member3_2_4 = {};
      var member3_2_5 = {};
      var member3_2_6 = {};
      var member3_2_7 = {};
      var member3_2_8 = {};
      var member3_2_9 = {};
      var member3_2_10 = {};
      var member3_2_11 = {};
      var member3_2_12 = {};
      var member3_2_13 = {};
      var member3_2_14 = {};
      var member3_2_15 = {};
      var member3_2_16 = {};
      var member3_2_17 = {};
      var member3_2_18 = {};
      var member3_2_19 = {};
      var member3_2_20 = {};
      var member3_2_21 = {};
      var member3_2_22 = {};
      var member3_2_23 = {};
      var member3_2_24 = {};
      var member3_2_25 = {};
      var member3_2_26 = {};
      var member3_2_27 = {};
      var member3_2_28 = {};
      var member3_2_29 = {};
      var member3_2_30 = {};
      var member3_2_31 = {};
      var member3_2_32 = {};
      var member3_2_33 = {};
      var member3_2_34 = {};
      var member3_2_35 = {};
      var member3_2_36 = {};
      var member3_2_37 = {};

//4.
var dimension4 = {};
  var hierarchy4 = {};
    var level4_1 = {};
      var member4_1_1 = {};
    var level4_2 = {};
      var member4_2_1={};
      var member4_2_2={};
      var member4_2_3 = {};
      var member4_2_4 = {};


//Push Operations

//1.
dimension1.LEVEL = "DIMENSION_UNIQUE_NAME";
dimension1.LABEL = "[Department]";
dimension1.CHILDREN = [];
  hierarchy1.LEVEL = "HIERARCHY_UNIQUE_NAME";
  hierarchy1.LABEL = "[Department]";
  hierarchy1.CHILDREN = [];
    level1_1.LEVEL  = "LEVEL_UNIQUE_NAME";
    level1_1.LABEL = "[Department].[(All)]";
    level1_1.CHILDREN = [];
      member1_1_1.LEVEL = "MEMBER_UNIQUE_NAME";
      member1_1_1.LABEL = "[Department].[All Departments]";
level1_1.CHILDREN.push(member1_1_1);
hierarchy1.CHILDREN.push(level1_1);

    level1_2.LEVEL  = "LEVEL_UNIQUE_NAME";
    level1_2.LABEL = "[Department].[Department]";
    level1_2.CHILDREN = [];
      member1_2_1.LEVEL = "MEMBER_UNIQUE_NAME";
      member1_2_1.LABEL = "[Department].[Executive Management]";
      level1_2.CHILDREN.push(member1_2_1);
      member1_2_2.LEVEL = "MEMBER_UNIQUE_NAME";
      member1_2_2.LABEL = "[Department].[Finance]";
      level1_2.CHILDREN.push(member1_2_2);
      member1_2_3.LEVEL = "MEMBER_UNIQUE_NAME";
      member1_2_3.LABEL = "[Department].[Human Resource]";
      level1_2.CHILDREN.push(member1_2_3);
      member1_2_4.LEVEL = "MEMBER_UNIQUE_NAME";
      member1_2_4.LABEL = "[Department].[Marketing & Communication]";
      level1_2.CHILDREN.push(member1_2_4);
      member1_2_5.LEVEL = "MEMBER_UNIQUE_NAME";
      member1_2_5.LABEL = "[Department].[Product Development]";
      level1_2.CHILDREN.push(member1_2_5);
      member1_2_6.LEVEL = "MEMBER_UNIQUE_NAME";
      member1_2_6.LABEL = "[Department].[Professional Services]";
      level1_2.CHILDREN.push(member1_2_6);
      member1_2_7.LEVEL = "MEMBER_UNIQUE_NAME";
      member1_2_7.LABEL = "[Department].[Sales]";
      level1_2.CHILDREN.push(member1_2_7);
hierarchy1.CHILDREN.push(level1_2);
dimension1.CHILDREN.push(hierarchy1);

//2.
dimension3.LEVEL = "DIMENSION_UNIQUE_NAME";
dimension3.LABEL = "[Positions]";
dimension3.CHILDREN = [];
  hierarchy3.LEVEL = "HIERARCHY_UNIQUE_NAME";
  hierarchy3.LABEL = "[Positions]";
  hierarchy3.CHILDREN = [];
    level3_1.LEVEL = "LEVEL_UNIQUE_NAME";
    level3_1.LABEL = "[Positions].[(All)]";
    level3_1.CHILDREN = [];
      member3_1_1.LEVEL = "MEMBER_UNIQUE_NAME";
      member3_1_1.LABEL = "[Positions].[All Positions]";
      level3_1.CHILDREN.push(member3_1_1);
hierarchy3.CHILDREN.push(level3_1);

    level3_2.LEVEL = "LEVEL_UNIQUE_NAME";
    level3_2.LABEL = "[Positions].[Positions]";
    level3_2.CHILDREN = [];
      member3_2_1.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_1.LABEL = "[Positions].[Account Executive]";
      level3_2.CHILDREN.push(member3_2_1);
      member3_2_2.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_2.LABEL = "[Positions].[Administration]";
      level3_2.CHILDREN.push(member3_2_2);
      member3_2_3.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_3.LABEL = "[Positions].[Administrative Assistant]";
      level3_2.CHILDREN.push(member3_2_3);
      member3_2_4.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_4.LABEL = "[Positions].[Analyst Relations]";
      level3_2.CHILDREN.push(member3_2_4);
      member3_2_5.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_5.LABEL = "[Positions].[CEO]";
      level3_2.CHILDREN.push(member3_2_5);
      member3_2_6.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_6.LABEL = "[Positions].[CFO]";
      level3_2.CHILDREN.push(member3_2_6);
      member3_2_7.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_7.LABEL = "[Positions].[CMO]";
      level3_2.CHILDREN.push(member3_2_7);
      member3_2_8.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_8.LABEL = "[Positions].[CTO]";
      level3_2.CHILDREN.push(member3_2_8);
      member3_2_9.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_9.LABEL = "[Positions].[Controller]";
      level3_2.CHILDREN.push(member3_2_9);
      member3_2_10.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_10.LABEL = "[Positions].[Corporate Compliance]";
      level3_2.CHILDREN.push(member3_2_10);
      member3_2_11.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_11.LABEL = "[Positions].[District Manager]";
      level3_2.CHILDREN.push(member3_2_11);
      member3_2_12.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_12.LABEL = "[Positions].[EOE]";
      level3_2.CHILDREN.push(member3_2_12);
      member3_2_13.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_13.LABEL = "[Positions].[Engineer]";
      level3_2.CHILDREN.push(member3_2_13);
      member3_2_14.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_14.LABEL = "[Positions].[Graphics]";
      level3_2.CHILDREN.push(member3_2_14);
      member3_2_15.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_15.LABEL = "[Positions].[HR Generalists]";
      level3_2.CHILDREN.push(member3_2_15);
      member3_2_16.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_16.LABEL = "[Positions].[HR Training]";
      level3_2.CHILDREN.push(member3_2_16);
      member3_2_17.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_17.LABEL = "[Positions].[IS]";
      level3_2.CHILDREN.push(member3_2_17);
      member3_2_18.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_18.LABEL = "[Positions].[Payroll]";
      level3_2.CHILDREN.push(member3_2_18);
      member3_2_19.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_19.LABEL = "[Positions].[Pre-Sales]";
      level3_2.CHILDREN.push(member3_2_19);
      member3_2_20.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_20.LABEL = "[Positions].[Press Relations]";
      level3_2.CHILDREN.push(member3_2_20);
      member3_2_21.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_21.LABEL = "[Positions].[Product Marketing Mgr]";
      level3_2.CHILDREN.push(member3_2_21);
      member3_2_22.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_22.LABEL = "[Positions].[QA Engineer]";
      level3_2.CHILDREN.push(member3_2_22);
      member3_2_23.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_23.LABEL = "[Positions].[QA Manager]";
      level3_2.CHILDREN.push(member3_2_23);
      member3_2_24.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_24.LABEL = "[Positions].[SVP HR]";
      level3_2.CHILDREN.push(member3_2_24);
      member3_2_25.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_25.LABEL = "[Positions].[SVP Partnerships]";
      level3_2.CHILDREN.push(member3_2_25);
      member3_2_26.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_26.LABEL = "[Positions].[SVP Services]";
      level3_2.CHILDREN.push(member3_2_26);
      member3_2_27.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_27.LABEL = "[Positions].[SVP Strategic Development]";
      level3_2.CHILDREN.push(member3_2_27);
      member3_2_28.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_28.LABEL = "[Positions].[SVP WW Operations]";
      level3_2.CHILDREN.push(member3_2_28);
      member3_2_29.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_29.LABEL = "[Positions].[Sales Rep]";
      level3_2.CHILDREN.push(member3_2_29);
      member3_2_30.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_30.LABEL = "[Positions].[Senior Consultant]";
      level3_2.CHILDREN.push(member3_2_30);
      member3_2_31.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_31.LABEL = "[Positions].[Senior Engineer]";
      level3_2.CHILDREN.push(member3_2_31);
      member3_2_32.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_32.LABEL = "[Positions].[Senior Sales Rep]";
      level3_2.CHILDREN.push(member3_2_32);
      member3_2_33.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_33.LABEL = "[Positions].[Services Mgr]";
      level3_2.CHILDREN.push(member3_2_33);
      member3_2_34.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_34.LABEL = "[Positions].[Staff Consultant]";
      level3_2.CHILDREN.push(member3_2_34);
      member3_2_35.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_35.LABEL = "[Positions].[Trainer]";
      level3_2.CHILDREN.push(member3_2_35);
      member3_2_36.LEVEL="MEMBER_UNIQUE_NAME";;
      member3_2_36.LABEL = "[Positions].[VP Engineering]";
      level3_2.CHILDREN.push(member3_2_36);
      member3_2_37.LEVEL="MEMBER_UNIQUE_NAME";
      member3_2_37.LABEL = "[Positions].[Writer]";
      level3_2.CHILDREN.push(member3_2_37);
hierarchy3.CHILDREN.push(level3_2);
dimension3.CHILDREN.push(hierarchy3);

//4.--------------------------
dimension4.LEVEL = "DIMENSION_UNIQUE_NAME";
dimension4.LABEL = "[Region]";
dimension4.CHILDREN =[];
  hierarchy4.LEVEL = "HIERARCHY_UNIQUE_NAME";
  hierarchy4.LABEL = "[Region]";
  hierarchy4.CHILDREN = [];
    level4_1.LEVEL = "LEVEL_UNIQUE_NAME";
    level4_1.LABEL = "[Region].[(All)]";
    level4_1.CHILDREN = [];
      member4_1_1.LEVEL = "MEMBER_UNIQUE_NAME";
      member4_1_1.LABEL = "[Region].[All Regions]";
level4_1.CHILDREN.push(member4_1_1);
hierarchy4.CHILDREN.push(level4_1);

    level4_2.LEVEL = "LEVEL_UNIQUE_NAME";
    level4_2.LABEL = "[Region].[Region]";
    level4_2.CHILDREN=[];
      member4_2_1.LEVEL = "MEMBER_UNIQUE_NAME";
      member4_2_1.LABEL = "[Region].[Central]";
      level4_2.CHILDREN.push(member4_2_1);

      member4_2_2.LEVEL = "MEMBER_UNIQUE_NAME";
      member4_2_2.LABEL = "[Region].[Eastern]";
      level4_2.CHILDREN.push(member4_2_2);

      member4_2_3.LEVEL = "MEMBER_UNIQUE_NAME";
      member4_2_3.LABEL = "[Region].[Southern]";
      level4_2.CHILDREN.push(member4_2_3);

      member4_2_4.LEVEL = "MEMBER_UNIQUE_NAME";
      member4_2_4.LABEL = "[Region].[Western]";
      level4_2.CHILDREN.push(member4_2_4);

  hierarchy4.CHILDREN.push(level4_2);
  dimension4.CHILDREN.push(hierarchy4);

  //2.
  dimension2.LEVEL = "DIMENSION_UNIQUE_NAME";
  dimension2.LABEL = "[Measures]";
  dimension2.CHILDREN = [];
    hierarchy2.LEVEL = "HIERARCHY_UNIQUE_NAME";
    hierarchy2.LABEL = "[Measures]";
    hierarchy2.CHILDREN = [];
      level2_1.LEVEL = "LEVEL_UNIQUE_NAME";
      level2_1.LABEL = "[Measures].[MeasuresLevel]";
      level2_1.CHILDREN = [];
        member2_1_1.LEVEL = "MEMBER_UNIQUE_NAME";
        member2_1_1.LABEL = "[Measures].[Actual]";
        level2_1.CHILDREN.push(member2_1_1);

        member2_1_2.LEVEL = "MEMBER_UNIQUE_NAME";
        member2_1_2.LABEL = "[Measures].[Budget]";
        level2_1.CHILDREN.push(member2_1_2);

        member2_1_3.LEVEL = "MEMBER_UNIQUE_NAME";
        member2_1_3.LABEL = "[Measures].[Variance]";
        level2_1.CHILDREN.push(member2_1_3);
hierarchy2.CHILDREN.push(level2_1);
dimension2.CHILDREN.push(hierarchy2);

  finalObj.push(dimension1);
  finalObj.push(dimension3);
  finalObj.push(dimension4);
  finalObj1.push(dimension2);
  fs.writeFile("./json/DimensionsTree.json",JSON.stringify(finalObj,null,2));
  fs.writeFile("./json/MeasuresTree.json",JSON.stringify(finalObj1,null,2));
